### PR TITLE
fix(places): use optional chaining when accessing the first place image

### PR DESCRIPTION
**Pull request by zainfathoni**
Fix some breaking changes introduced in #35

### CODE REVIEW

**Review by mhaidarhanif — APPROVED** [review]
@zainfathoni Alright this should be safer now

cc @mazipan

**Comment by mhaidarhanif** [comment]
@zainfathoni While we are at it, we can also condition the image to now be shown when the images don't exist

**Comment by zainfathoni** [comment]
Updated. It should be fixed now.
https://kawalmasjid-git-hotfix-optional-chaining-zainfathoni.vercel.app/places/cek-q5j6gfueak

Nice catch @mhaidarhanif, but this bug indicates that the form is introducing a loophole where an image can be created with an empty string value. 😅

**Comment by mhaidarhanif** [comment]
Yes, also that's why we need to confirm again, is it truly allowed or not for people to submit without the place photo and QR code?

If not, then we can implement in the next PR or here, to improve the Zod schema so both images are required

**Comment by zainfathoni** [comment]
We allowed for that permissive Zod schema because we didn't have the `edit` pages implemented yet, wasn't it?
In that case, trying to make it required now would force us to implement the `edit` pages right away, which would take way longer than what this hotfix is intended to be.

**Comment by mhaidarhanif** [comment]
True, let's consider this PR as done then. We'll improve that in the next one.

**Comment by zainfathoni** [comment]
Please approve this PR in your review, then @mhaidarhanif 😅

**Review by mhaidarhanif — APPROVED** [review]
Alright, approved 👍

I thought to double check with your thoughts, before we conclude

**Pull request merged**
